use_frameworks!

platform :ios, '8.0'

target 'GDorisTransition_Example' do
  pod 'GDorisTransition', :path => '../'
  pod 'Masonry'
  target 'GDorisTransition_Tests' do
    inherit! :search_paths
  end
end
